### ISSUE TITLE
Add CUDA support to build

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/libhwloc-feedstock#43]
### Comment:

hwloc has CUDA support via both cudart and NVML and then can dynamically use them at build time. It would be nice to enable them in the build.

**Comment by jan-janssen** [comment]
This would really help a lot.

**Comment by jan-janssen** [comment]
I tried fixing this issue in https://github.com/conda-forge/libhwloc-feedstock/pull/46

**Comment by jan-janssen** [comment]
I did a couple of tests and so far everything seems to work like it should - `libhwloc` is recognizing the GPUs. The only thing left to change is the naming of the packages, this is done in https://github.com/conda-forge/libhwloc-feedstock/pull/53 . The new names are going to be `libhwloc==2.9.1=cuda110_hdcc1471_4` following the `pytorch` naming scheme.
